[tool.poetry]
name = "pods"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.0"
gunicorn = "^23.0.0"
pymupdf = "^1.25.4"
regex = "^2024.11.6"
rapidfuzz = "^3.12.2"
pytesseract = "^0.3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"